---
- name: Update apt cache and upgrade all packages
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
    cache_valid_time: 3600
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
    - zsh
    - git
    - curl
    - tmux
    - expect

- name: Change shell to zsh for kali user
  ansible.builtin.user:
    name: kali
    shell: /bin/zsh

- name: Change shell to zsh for kali user
  ansible.builtin.user:
    name: root
    shell: /bin/zsh
  become: true

- name: Clone the repository
  ansible.builtin.git:
    repo: 'https://github.com/caarlos0/dotfiles.zsh.git'
    dest: '{{ ansible_env.HOME }}/.dotfiles'
  become: false
    
- name: Ensure bootstrap script is executable
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.dotfiles/script/bootstrap'
    mode: '0755'
  become: false

- name: Run the bootstrap script with expect
  ansible.builtin.shell: |
    /usr/bin/expect -c '
    spawn ./script/bootstrap
    expect "What is your github author name?"
    send "mennobo\r"
    expect "What is your github author email?"
    send "mbezema@pm.me\r"
    interact
    '
  args:
    chdir: '{{ ansible_env.HOME }}/.dotfiles'
  become: false

- name: Copy config.zsh
  copy: 
    src: config.zsh
    dest: "/home/kali/.dotfiles/zsh/config.zsh"
  become: false

- name: Copy .tmux.config
  copy: 
    src: .tmux.conf
    dest: "{{ lookup('env','HOME') }}/.tmux.conf"
  become: false

- name: Clone tmux-plugins/tpm repository
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env','HOME') }}/.tmux/plugins/tpm"
  become: false

# - name: Clone powerlevel10k
#   git:
#     repo: 'https://github.com/romkatv/powerlevel10k.git'
#     dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
#     depth: 1

# - name: Clone zsh-autosuggestions
#   git:
#     repo: 'https://github.com/zsh-users/zsh-autosuggestions'
#     dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

# - name: Clone zsh-syntax-highlighting
#   git:
#     repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
#     dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

# - name: Clone fast-syntax-highlighting
#   git:
#     repo: 'https://github.com/zdharma-continuum/fast-syntax-highlighting.git'
#     dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"

# - name: Clone powerlevel10k
#   git:
#     repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
#     dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/zsh-autocomplete"
#     depth: 1
