---
- name: Install ffuf
  apt:
    name: ffuf
    state: present
    update_cache: yes

- name: Clone PenTestical/sqli repository
  ansible.builtin.git:
    repo: 'https://github.com/PenTestical/sqli.git'
    dest: '/tmp/sqli'

- name: Copy files to destination
  ansible.builtin.copy:
    src: 'sqli_wordlist.txt'
    dest: '/usr/share/wfuzz/wordlist/Injections/'
    remote_src: no
  
- name: Install tools using pipx
  ansible.builtin.command:
    cmd: pipx install impacket

- name: Create alias for autorecon
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'alias autorecon="sudo $(which autorecon)"'
    state: present

- name: Clone PowerSploit repository
  ansible.builtin.git:
    repo: 'https://github.com/PowerShellMafia/PowerSploit.git'
    dest: '/opt/PowerSploit'

- name: Create /opt/ligolo-ng directory
  ansible.builtin.file:
    path: /opt/ligolo-ng
    state: directory
    mode: '0755'

- name: Download ligolo-ng Linux agent
  ansible.builtin.get_url:
    url: https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_Linux_amd64.tar.gz
    dest: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_arm64.tar.gz

- name: Download ligolo-ng Linux agent
  ansible.builtin.get_url:
    url: https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_Linux_amd64.tar.gz
    dest: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_amd64.tar.gz

- name: Download ligolo-ng Linux proxy
  ansible.builtin.get_url:
    url: https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_proxy_0.7.5_Linux_arm64.tar.gz
    dest: /opt/ligolo-ng/ligolo-ng_proxy_0.7.5_Linux_arm64.tar.gz

- name: Download ligolo-ng Windows agent
  ansible.builtin.get_url:
    url: https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_windows_amd64.zip
    dest: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_windows_amd64.zip

- name: Extract ligolo-ng Linux agent amd
  ansible.builtin.unarchive:
    src: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_amd64.tar.gz
    dest: /opt/ligolo-ng/
    remote_src: yes

- name: Rename extracted files
  ansible.builtin.command:
    cmd: mv /opt/ligolo-ng/agent /opt/ligolo-ng/lin-agent-amd64 

- name: Extract ligolo-ng Linux agent
  ansible.builtin.unarchive:
    src: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_arm64.tar.gz
    dest: /opt/ligolo-ng/
    remote_src: yes

- name: Rename extracted files
  ansible.builtin.command:
    cmd: mv /opt/ligolo-ng/agent /opt/ligolo-ng/lin-agent-arm64

- name: Extract ligolo-ng Linux proxy
  ansible.builtin.unarchive:
    src: /opt/ligolo-ng/ligolo-ng_proxy_0.7.5_Linux_arm64.tar.gz
    dest: /opt/ligolo-ng/
    remote_src: yes

- name: Rename extracted files
  ansible.builtin.command:
    cmd: mv /opt/ligolo-ng/proxy /opt/ligolo-ng/lin-proxy-arm64

- name: Extract ligolo-ng Windows agent
  ansible.builtin.unarchive:
    src: /opt/ligolo-ng/ligolo-ng_agent_0.7.5_windows_amd64.zip
    dest: /opt/ligolo-ng/
    remote_src: yes

- name: Clean up downloaded files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_amd64.tar.gz
    - /opt/ligolo-ng/ligolo-ng_agent_0.7.5_Linux_arm64.tar.gz
    - /opt/ligolo-ng/ligolo-ng_proxy_0.7.5_Linux_arm64.tar.gz
    - /opt/ligolo-ng/ligolo-ng_agent_0.7.5_windows_amd64.zip

- name: Clone Ghostpack-CompiledBinaries repository
  ansible.builtin.git:
    repo: 'https://github.com/r3motecontrol/Ghostpack-CompiledBinaries.git'
    dest: '/opt/Ghostpack-CompiledBinaries'

- name: Clone Nishang repository
  ansible.builtin.git:
    repo: 'https://github.com/samratashok/nishang.git'
    dest: '/opt/nishang'

- name: Clone Mimikatz repository
  ansible.builtin.git:
    repo: 'https://github.com/ParrotSec/mimikatz.git'
    dest: '/opt/mimikatz'

- name: Clone JAWS repository
  ansible.builtin.git:
    repo: 'https://github.com/411Hall/JAWS.git'
    dest: '/opt/JAWS'

- name: Download winPEASany.exe
  ansible.builtin.get_url:
    url: https://github.com/peass-ng/PEASS-ng/releases/download/20250202-a3a1123d/winPEASany.exe
    dest: /opt/winPEASany.exe

- name: Download linpeas.sh
  ansible.builtin.get_url:
    url: https://github.com/peass-ng/PEASS-ng/releases/download/20250202-a3a1123d/linpeas.sh
    dest: /opt/linpeas.sh
    mode: '0755'
