---
- name: Change user password
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"

- name: Change root password
  user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"
